name: introduction_screen
description: Introduction screen for apps
version: 0.0.2
author: Jean-Charles Moussé <jeancharles.msse@gmail.com>
homepage: http://github.com/pyozer/introduction_screen

dependencies:
  flutter:
    sdk: flutter

  dots_indicator: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'