name: introduction_screen
description: Introduction/Onboarding package for flutter app with some customizations possibilities
version: 1.0.5+2
author: Jean-Charles Moussé <jeancharles.msse@gmail.com>
homepage: https://github.com/pyozer/introduction_screen

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_web: any
  dots_indicator: ^0.0.5+1

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
