name: introduction_screen
description: Introduction/Onboarding package for flutter app with some customizations possibilities
version: 1.0.5+2
author: Jean-Charles Moussé <jeancharles.msse@gmail.com>
homepage: https://github.com/pyozer/introduction_screen

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any
  dots_indicator:
    git:
      url: https://github.com/pyozer/dots_indicator
      ref: e7fe97e48b6a446924801a68b7a358e3d80b2d6b

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
