name: introduction_screen
description: Introduction screen for apps
version: 0.0.1
author: Jean-Charles Moussé <jeancharles.msse@gmail.com>
homepage: http://github.com/pyozer/introduction_screen

dependencies:
  flutter:
    sdk: flutter
  dots_indicator:
    git: git://github.com/pyozer/dots_indicator

dev_dependencies:
  flutter_test:
    sdk: flutter